---
title: Nicolas Thiry
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'Hi, my name is Nicolas Thiry and I am a front-developer. This is my
  blog where you can read about everything I am working on.

'
author: Nicolas Thiry
email: n.thiry92@gmail.com
baseurl: 
url: http://www.nicolasthy.xyz
image: nicolas-thiry.jpg
twitter_username: nicolasthy
github_username: nicolasthy
dribbble_username: nicolasthy
linkedin_username: nicolasthy
instagram_username: nicolasthy
include:
  - _pages
markdown: kramdown
permalink: "/:title/"
sass:
  style: compressed
plugins:
- jekyll-redirect-from
