# Site settings
title: Nicolas Thiry
description: >
    Hi, my name is Nicolas Thiry and I am a front-developer. This is my blog where you can read about everything I am working on.
author: Nicolas Thiry
email: n.thiry92@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.nicolasthy.xyz" # the base hostname & protocol for your site
image: nicolas-thiry.jpg
twitter_username: nicolasthy
github_username:  nicolasthy

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:title/
sass:
    style: compressed
