# Site settings
title: EPSI Notes
email: nicolas.thiry@epsi.fr
description: > # this means to ignore newlines until "baseurl:"
  Ce site est destiné aux élèves de la classe I4 Alternance de l'EPSI Lyon.
baseurl: "/epsi-notes" # the subpath of your site, e.g. /blog/
url: "http://nicolasthy.github.io/epsi-notes" # the base hostname & protocol for your site
twitter_username: nicolasthy
github_username:  nicolasthy

# Build settings
markdown: kramdown

paginate: 6
paginate_path: "/page:num/"
